/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cc4p1.snake.ui;

import cc4p1.snake.client.GameClient;
import cc4p1.snake.server.ServerMain;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.net.Inet4Address;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author Albert
 */
public class GameWindow extends javax.swing.JFrame implements IBoardUpdater, KeyListener {
    private GameClient localClient;
    private boolean serverStarted = false;
    private boolean connected = false;

    /**
     * Creates new form GameWindowClient
     */
    public GameWindow() {
        initComponents();

        // Configurando los KeyListener para las teclas de flecha
        Board.addKeyListener(this);
        Board.setFocusable(true);
        this.addKeyListener(this);
        this.setFocusable(true);
    }

    public void updateBoard(String boardText) {
        SwingUtilities.invokeLater(() -> Board.setText(boardText));
    }

    public void updateScores(String scoresText) {
        System.out.println("DEBUG updateScores() llamado con: '" + scoresText + "'");
        SwingUtilities.invokeLater(() -> {
            jPuntuacionServer.setText(scoresText);
            System.out.println("DEBUG updateScores() - TextArea actualizado");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Board = new javax.swing.JTextArea();
        UpBtn = new javax.swing.JButton();
        LeftBtn = new javax.swing.JButton();
        RightBtn = new javax.swing.JButton();
        DownBtn = new javax.swing.JButton();
        StartServerBtn = new javax.swing.JButton();
        ConnectBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPuntuacionServer = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Board.setEditable(false);
        Board.setColumns(30);
        Board.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Board.setRows(12);
        jScrollPane1.setViewportView(Board);

        UpBtn.setText("^");
        UpBtn.setFocusPainted(false);
        UpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpBtnActionPerformed(evt);
            }
        });

        LeftBtn.setText("<");
        LeftBtn.setFocusPainted(false);
        LeftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftBtnActionPerformed(evt);
            }
        });

        RightBtn.setText(">");
        RightBtn.setFocusPainted(false);
        RightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightBtnActionPerformed(evt);
            }
        });

        DownBtn.setText("v");
        DownBtn.setFocusPainted(false);
        DownBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownBtnActionPerformed(evt);
            }
        });

        StartServerBtn.setText("START SERVER");
        StartServerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartServerBtnActionPerformed(evt);
            }
        });

        ConnectBtn.setText("CONNECT");
        ConnectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectBtnActionPerformed(evt);
            }
        });

        jPuntuacionServer.setColumns(20);
        jPuntuacionServer.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jPuntuacionServer.setRows(5);
        jScrollPane2.setViewportView(jPuntuacionServer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(LeftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(RightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(DownBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(UpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)))
                    .addComponent(StartServerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConnectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(StartServerBtn)
                .addGap(18, 18, 18)
                .addComponent(ConnectBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(UpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RightBtn)
                    .addComponent(LeftBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DownBtn)
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartServerBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_StartServerBtnActionPerformed
        // TODO add your handling code here:
        try {
            int port = ServerMain.getCurrentPort();

            ServerMain.startServer(port);
            serverStarted = true;
            StartServerBtn.setEnabled(false);

            Board.setText("Servidor iniciado en puerto " + port + "\nEsperando jugadores...");
        } catch (Exception e) {
            Board.setText("ERROR al iniciar servidor:\n" + e.getMessage() + "\n\nProbable causa: Puerto "
                    + ServerMain.getCurrentPort() + " ocupado");
            e.printStackTrace();
        }
    }// GEN-LAST:event_StartServerBtnActionPerformed

    private void UpBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UpBtnActionPerformed
        // TODO add your handling code here:
        if (connected && localClient != null) {
            localClient.sendDirection("UP");
            Board.requestFocus();
        }
    }// GEN-LAST:event_UpBtnActionPerformed

    private void RightBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RightBtnActionPerformed
        // TODO add your handling code here:
        if (connected && localClient != null) {
            localClient.sendDirection("RIGHT");
            Board.requestFocus();
        }
    }// GEN-LAST:event_RightBtnActionPerformed

    private void DownBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DownBtnActionPerformed
        // TODO add your handling code here:
        if (connected && localClient != null) {
            localClient.sendDirection("DOWN");
            Board.requestFocus();
        }
    }// GEN-LAST:event_DownBtnActionPerformed

    private void ConnectBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ConnectBtnActionPerformed
        // TODO add your handling code here:
        if (!serverStarted) {
            Board.setText("ERROR: Primero debes iniciar el servidor");
            return;
        }

        String host;
        try {
            host = Inet4Address.getLocalHost().getHostAddress();
        } catch (UnknownHostException ex) {
            Logger.getLogger(GameWindow.class.getName()).log(Level.SEVERE, null, ex);
            Board.setText("ERROR: No se puede obtener la dirección IP local\n" + ex.getMessage());
            return;
        }
        int port = ServerMain.getCurrentPort();

        try {
            // Esperar un momento para que el servidor esté listo
            Thread.sleep(500);

            localClient = new GameClient(host, port, this);
            localClient.start();
            localClient.sendJoin("Server");

            connected = true;

            Board.requestFocus();

        } catch (Exception e) {
            Board.setText("ERROR al conectar al servidor:\n" + e.getMessage() + "\n\nServidor: " + host + ":" + port);
            e.printStackTrace();
        }
    }// GEN-LAST:event_ConnectBtnActionPerformed

    private void NextLevelBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NextLevelBtnActionPerformed
        // TODO add your handling code here:
        if (connected && localClient != null) {
            // Enviar comando para cambiar nivel
            localClient.sendLevelCommand("NEXT");
            Board.requestFocus();
        } else {
            Board.setText("ERROR: Debes estar conectado para cambiar de nivel");
        }
    }// GEN-LAST:event_NextLevelBtnActionPerformed

    private void LeftBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LeftBtnActionPerformed
        // TODO add your handling code here:
        if (connected && localClient != null) {
            localClient.sendDirection("LEFT");
            Board.requestFocus();
        }
    }// GEN-LAST:event_LeftBtnActionPerformed

    // Implementación de KeyListener para las teclas de flecha
    @Override
    public void keyPressed(KeyEvent e) {
        if (connected && localClient != null) {
            switch (e.getKeyCode()) {
                case KeyEvent.VK_UP:
                    localClient.sendDirection("UP");
                    break;
                case KeyEvent.VK_DOWN:
                    localClient.sendDirection("DOWN");
                    break;
                case KeyEvent.VK_LEFT:
                    localClient.sendDirection("LEFT");
                    break;
                case KeyEvent.VK_RIGHT:
                    localClient.sendDirection("RIGHT");
                    break;
            }
            Board.requestFocus();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        // No necesitamos manejar cuando se suelta la tecla
    }

    @Override
    public void keyTyped(KeyEvent e) {
        // No necesitamos manejar el typing de caracteres
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Board;
    private javax.swing.JButton ConnectBtn;
    private javax.swing.JButton DownBtn;
    private javax.swing.JButton LeftBtn;
    private javax.swing.JButton RightBtn;
    private javax.swing.JButton StartServerBtn;
    private javax.swing.JButton UpBtn;
    private javax.swing.JTextArea jPuntuacionServer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
