/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cc4p1.snake.ui;

import cc4p1.snake.client.GameClient;
import cc4p1.snake.server.ServerMain;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author Albert
 */
public class GameWindowClient extends javax.swing.JFrame implements IBoardUpdater, KeyListener {
    // Permitir reactivar el botón de conexión tras perder

    private GameClient gameClient;
    private boolean connected = false;

    /**
     * Creates new form GameWindow
     */
    public GameWindowClient() {
        initComponents();
        setTitle("Snake Multijugador");

        // Configurando KeyListener para las flechas
        Board.addKeyListener(this);
        Board.setFocusable(true);
        this.addKeyListener(this);
        this.setFocusable(true);

        // Dar foco al board para que reciba las teclas inmediatamente
        Board.requestFocus();
    }

    /**
     * This method is Scalled from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IPInput = new javax.swing.JTextField();
        PortInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ConnectBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Board = new javax.swing.JTextArea();
        RightBtn = new javax.swing.JButton();
        LeftBtn = new javax.swing.JButton();
        UpBtn = new javax.swing.JButton();
        DownBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        UsernameInput = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPuntuacionCliente = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        IPInput.setBorder(null);

        PortInput.setBorder(null);

        jLabel1.setText("IP");

        jLabel2.setText("PORT");

        ConnectBtn.setText("CONNECT");
        ConnectBtn.setFocusPainted(false);
        ConnectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectBtnActionPerformed(evt);
            }
        });

        Board.setEditable(false);
        Board.setColumns(30);
        Board.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        Board.setRows(12);
        jScrollPane1.setViewportView(Board);

        RightBtn.setText(">");
        RightBtn.setFocusPainted(false);
        RightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightBtnActionPerformed(evt);
            }
        });

        LeftBtn.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        LeftBtn.setText("<");
        LeftBtn.setFocusPainted(false);
        LeftBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftBtnActionPerformed(evt);
            }
        });

        UpBtn.setText("^");
        UpBtn.setFocusPainted(false);
        UpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpBtnActionPerformed(evt);
            }
        });

        DownBtn.setText("v");
        DownBtn.setFocusPainted(false);
        DownBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("PLAYER");

        UsernameInput.setBorder(null);

        jPuntuacionCliente.setEditable(false);
        jPuntuacionCliente.setColumns(20);
        jPuntuacionCliente.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jPuntuacionCliente.setRows(5);
        jScrollPane2.setViewportView(jPuntuacionCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(PortInput)
                                                        .addComponent(IPInput, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                111, Short.MAX_VALUE)
                                                        .addComponent(UsernameInput))
                                                .addContainerGap(16, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                layout.createSequentialGroup()
                                                                        .addComponent(ConnectBtn)
                                                                        .addGap(52, 52, 52))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(LeftBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                42,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(RightBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                42,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(DownBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                42,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(29, 29, 29))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(UpBtn,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                42,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGap(30, 30, 30)))
                                                                .addGap(41, 41, 41)))))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(IPInput,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(PortInput, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2))
                                                .addGap(12, 12, 12)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel3)
                                                        .addComponent(UsernameInput,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(29, 29, 29)
                                                .addComponent(ConnectBtn)
                                                .addGap(102, 102, 102)
                                                .addComponent(UpBtn))
                                        .addComponent(jScrollPane1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(RightBtn)
                                                        .addComponent(LeftBtn))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(DownBtn))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(16, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateBoard(String boardText) {
        SwingUtilities.invokeLater(() -> Board.setText(boardText));
    }

    public void updateScores(String scoresText) {
        System.out.println("DEBUG updateScores() llamado con: '" + scoresText + "'");
        SwingUtilities.invokeLater(() -> {
            jPuntuacionCliente.setText(scoresText);
            System.out.println("DEBUG updateScores() - TextArea actualizado");
        });
    }

    private void ConnectBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ConnectBtnActionPerformed
        // TODO add your handling code here:
        // StartServerBtn.setEnabled(false);
        String host = IPInput.getText().trim();
        int port = Integer.parseInt(PortInput.getText().trim());
        String username = UsernameInput.getText().trim();

        try {
            gameClient = new GameClient(host, port, this);
            gameClient.start();
            gameClient.sendJoin(username);

            connected = true;
            IPInput.setEnabled(false);
            PortInput.setEnabled(false);
            UsernameInput.setEnabled(false);

            Board.requestFocus();
        } catch (IOException e) {
            return;
        }

    }// GEN-LAST:event_ConnectBtnActionPerformed

    private void UpBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UpBtnActionPerformed
        // TODO add your handling code here:
        if (connected && gameClient != null) {
            gameClient.sendDirection("UP");
            Board.requestFocus();
        }
    }// GEN-LAST:event_UpBtnActionPerformed

    private void DownBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_DownBtnActionPerformed
        // TODO add your handling code here:
        if (connected && gameClient != null) {
            gameClient.sendDirection("DOWN");
            Board.requestFocus();
        }
    }// GEN-LAST:event_DownBtnActionPerformed

    private void RightBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RightBtnActionPerformed
        // TODO add your handling code here:
        if (connected && gameClient != null) {
            gameClient.sendDirection("RIGHT");
            Board.requestFocus();
        }
    }// GEN-LAST:event_RightBtnActionPerformed

    private void LeftBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_LeftBtnActionPerformed
        // TODO add your handling code here:
        if (connected && gameClient != null) {
            gameClient.sendDirection("LEFT");
            Board.requestFocus();
        }
    }// GEN-LAST:event_LeftBtnActionPerformed

    @Override
    public void keyPressed(KeyEvent e) {
        if (connected && gameClient != null) {
            switch (e.getKeyCode()) {
                case KeyEvent.VK_UP:
                    gameClient.sendDirection("UP");
                    break;
                case KeyEvent.VK_DOWN:
                    gameClient.sendDirection("DOWN");
                    break;
                case KeyEvent.VK_LEFT:
                    gameClient.sendDirection("LEFT");
                    break;
                case KeyEvent.VK_RIGHT:
                    gameClient.sendDirection("RIGHT");
                    break;
            }
            Board.requestFocus();
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        // No necesitamos manejar cuando se suelta la tecla
    }

    @Override
    public void keyTyped(KeyEvent e) {
        // No necesitamos manejar el typing de caracteres
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Board;
    private javax.swing.JButton ConnectBtn;
    private javax.swing.JButton DownBtn;
    private javax.swing.JTextField IPInput;
    private javax.swing.JButton LeftBtn;
    private javax.swing.JTextField PortInput;
    private javax.swing.JButton RightBtn;
    private javax.swing.JButton UpBtn;
    private javax.swing.JTextField UsernameInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextArea jPuntuacionCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
